#ifndef DEFS_H
#define DEFS_H

#define OPTIONS_BANNER 20
#define PADDING 10
#define DISPLAY_BANNER (PADDING * 2 + 64)
#define TILE_SIZE 32
#define BOARD_Y_START (OPTIONS_BANNER + DISPLAY_BANNER + PADDING)
#define MIN_WINDOW_WIDTH (PADDING * 4 + 32 * 6 + 64)

#endif